config/routes.rb
Rails.application.routes.draw do
  get 'documents/:id' => 'home#show', :as => :documents
  get 'home/index'
  get 'home/administration', :path => "administration"
  get 'home/smq', :path => "smq"
  get 'home/external', :path => "external"
  get 'news/index', :path => "news"
  get 'news/:alias' => 'news#show', :as => :news
  get 'pages/:alias' => 'pages#show', :as => :pages

  root to: "home#index"
  devise_for :users
  devise_for :admins

  namespace "api" do
    resources :documents
    resources :users
    resources :categories
    resources :news
    resources :pages
    resources :workers
    post 'workers/find/' => 'workers#find'
  end

end

app/models/news.rb
class News < ActiveRecord::Base
	validates :alias, uniqueness: true, presence: true
end

app/controllers/api/news_controller.rb
module API
  class NewsController < ApplicationController
    # GET /News
    # GET /News.json
    def index
      @news = News.all

      render json: @news
    end

    # GET /News/1
    # GET /News/1.json
    def show
      @News = News.find(params[:id])

      render json: @News
    end

    # POST /News
    # POST /News.json
    def create
      @News = News.new(tl_params)

      if @News.save
        render json: @News, status: :created
      else
         render json: @News.errors, status: :unprocessable_entity
      end
    end

    # PATCH/PUT /News/1
    # PATCH/PUT /News/1.json
    def update
      @News = News.find(params[:id])

      if @News.update(tl_params)
        head :no_content
      else
        render json: @News.errors, status: :unprocessable_entity
      end
    end

    # DELETE /News/1
    # DELETE /News/1.json
    def destroy
      @News = News.find(params[:id])
      @News.destroy

      head :no_content
    end
    private
    def tl_params
      params.require(:news).permit(:title, :body, :alias)
    end
  end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController

  def index
    @news = News.all
  end

  def show
    @news = News.find_by(alias: params[:alias])
  end
end

app/views/news/index.html.erb
<% @news.each do |news| %>
<div class="panel panel-default">
  <div class="panel-heading">
    <%= link_to news.title, news_path(news.alias) %>
  </div>
  <div class="panel-body ellipsis multiline"><%= news.body.html_safe %></div>
</div>
<% end %>

<script type="text/javascript">
$(".ellipsis").ellipsis();
</script>

app/views/news/show.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <%= @news.title %>
  </div>
  <div class="panel-body"><%= @news.body.html_safe %></div>
</div>