config/routes.rb
Rails.application.routes.draw do
  get 'documents/:id' => 'home#show', :as => :documents
  get 'home/index'
  get 'home/administration', :path => "administration"
  get 'home/smq', :path => "smq"
  get 'home/external', :path => "external"
  get 'news/index', :path => "news"
  get 'news/:alias' => 'news#show', :as => :news
  get 'pages/:alias' => 'pages#show', :as => :pages

  root to: "home#index"
  devise_for :users
  devise_for :admins

  namespace "api" do
    resources :documents
    resources :users
    resources :categories
    resources :news
    resources :pages
    resources :workers
    post 'workers/find/' => 'workers#find'
  end

end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Адміністрація</title>
  <%= stylesheet_link_tag    'administration', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'admin', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.min.css" />
  <%= favicon_link_tag %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand brand">Система менеджменту якості НАУ</a>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <li>
          <% if admin_signed_in? %>
            <%= link_to 'Вийти', destroy_user_session_path, :method => :delete %>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</div>
<%= yield %>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Система менеджменту якості НАУ</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= favicon_link_tag %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="navbar navbar-fixed-top navbar-inverse" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Система менеджменту якості НАУ", root_url, :class => "navbar-brand brand" %>
      </div>
      <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav navbar-right">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">СМЯ<span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to "Новини СМЯ", news_index_path %></li>
              <% Pages.all.each do |page| %>
                <li><%= link_to page.name, pages_path(page.alias) %></li>
              <% end %>
            </ul>
          </li>
          <%= active_li_tag "Документація СМК", home_smq_url %>
          <%= active_li_tag "Зовнішня документація", home_external_url %>
          <% if current_user %>
            <li><%= link_to 'Вийти', destroy_user_session_path, :method => :delete %></li>
          <% else %>
            <li><%= link_to 'Увійти', new_user_session_path %></li>
          <% end %>
        </ul>
      </div><!-- /.nav-collapse -->
    </div><!-- /.container -->
  </div><!-- /.navbar -->

  <div class="container">
    <div class="row row-offcanvas row-offcanvas-left">
      <div class="col-xs-6 col-sm-3 sidebar-offcanvas" id="sidebar" role="navigation">
        <div class="list-group">
          <% Category.all.each do |category| %>
            <%= link_to category.name, documents_path(category), :class => is_active?(documents_path(category), "active", "list-group-item") %>
          <% end %>
        </div>
      </div><!--/span-->
      <div class="col-xs-12 col-sm-9">
        <p class="pull-left visible-xs">
          <button type="button" class="btn btn-primary btn-xs" data-toggle="offcanvas">Меню</button>
        </p>
        <div class="jumbotron logo">
        </div>
        <div class="row">
          <div class="col-12">
            <% if flash[:notice] %>
              <div class="alert alert-success" role="alert"><%= flash[:notice] %></div>
            <% elsif flash[:alert]  %>
              <div class="alert alert-danger" role="alert"><%= flash[:alert] %></div>
            <% end %>
            <%= yield %>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.col -->
    </div><!-- /.row -->
    <hr>

    <footer>
      <div>2014 &copy; Система менеджменту якості НАУ</div>
      <a href="http://www.bureauveritas.com.ua/" target="_blank">
        <div class="certificate pull-right"></div>
      </a>
    </footer>
  </div><!-- /.container -->
</body>
</html>